### ISSUE TITLE
Add support for other aggregate functions

### ISSUE THREAD

**Issue by iagopiimenta** [k0kubun/activerecord-precount#28]
Any interest in adapting the gem to support other aggregate functions? Like Sum, Avg, Max, etc ?

**Comment by k0kubun** [comment]
Interesting. But activerecord-precount makes it hard to implement them because each of them would require association definition. For maintainability, I prefer to implement that in https://github.com/k0kubun/activerecord-precounter. Closing this in favor of it. If you really need it, please file an issue in that repository.
