### ISSUE TITLE
Rails 5.2 support?

### ISSUE THREAD

**Issue by guilleiguaran** [k0kubun/activerecord-precount#31]
Looks like multiple changes in Active Record 5.2 internals have broken this library.

Is 5.2 support planned or is recommended to use activerecord-precounter instead?

If 5.2 support is planned I can send some PRs but it will be pretty hard to keep compatibility between <5.1 and 5.2 in the same codebase (most of the changes in 5.2 involves changes in the signature of patched methods)

**Comment by k0kubun** [comment]
> Is 5.2 support planned or is recommended to use activerecord-precounter instead?

At least I don't have a plan to support it by myself and there is no other maintainer. That's why I created activerecord-precounter, but if there is a person who can send a patch to activerecord-precount and maintain, it would be the best.

> If 5.2 support is planned I can send some PRs but it will be pretty hard to keep compatibility between <5.1 and 5.2 in the same codebase

I know it's hard, and I'm personally fine to drop 5.1 support when supporting 5.2. We can create 5-1 branch or something later if we need an extra release for old versions.

**Comment by guilleiguaran** [comment]
Heads up, we decided to move to [activerecord-precounter](https://github.com/k0kubun/activerecord-precounter) and I suggest to everyone reading this issue to do the same 😊
